# Generated by Django 3.2.4 on 2021-06-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('article', '0003_auto_20210607_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='author.author', verbose_name='Author'),
        ),
        migrations.DeleteModel(
            name='ArticleAuthor',
        ),
    ]
