# Generated by Django 3.2.4 on 2021-06-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210607_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='icon_reverse',
        ),
        migrations.RemoveField(
            model_name='article',
            name='icon_rgb',
        ),
    ]
