# Generated by Django 3.2.4 on 2021-06-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='body',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
